### ISSUE TITLE
404 error when trying to login (was working fine a few hours ago)

### ISSUE THREAD

**Issue by sudhxnva** [Sprayxe/valorant.js#13]
The library was working fine like 10 hours ago, but now I'm not able to complete the OAuth process to login. 

Here's the error: 
```json
 {
    "error": {
      "statusCode": 404,
      "name": "RouterServiceError",
      "error": "invalid_request",
      "message": "not_found"
    }
  }
```

I noticed that there was a similar issue that was resolved a while ago. Any idea why this is happening?

**Comment by marcel-wrld** [comment]
I've experienced that error aswell. Sadly, I don't know why this is happening, I'm assuming that Riot deployed a patch. I will update the library as soon as a fix was found!

**Comment by sudhxnva** [comment]
Are you sure Riot deployed a patch? They did say that they [fixed an issue](https://twitter.com/PlayVALORANT/status/1389783270502526976?s=20) recently, but valorant-api.com doesn't show any new patch deploys ([here](https://valorant-api.com/v1/version) is the endpoint). 

Also, I'm not sure if this helps, but here's a python script that uses a similar authentication with the OAuth API and it is still working fine: https://github.com/OwOHamper/Valorant-item-shop-discord-bot

**Comment by marcel-wrld** [comment]
Yea I think it is because I am missing cookies when sending the request. I'm gonna try fixing it.

**Comment by marcel-wrld** [comment]
I think I fixed it. Download the latest version of the library using 'npm i valorant.js' and let me know if it works!

**Comment by sudhxnva** [comment]
Great! It's working now! Thanks a ton man!
