### ISSUE TITLE
Implement functionality for logout()

### ISSUE THREAD

**Issue by ARKEOLOGIST** [Sprayxe/valorant.js#4]
Currently, there is no way to programmatically log out. One quick look through the code suggests that a function logout() exists, but it hasn't been worked on yet.

I want to use this in production, and I really hope this can be worked upon.

**Comment by BobbyESP** [comment]
I will try to do the login in 3 hours (im not at home). I know the way to do it, so let me update it. Thanks

**Comment by marcel-wrld** [comment]
Currently, we do not know the endpoint for logging out.Though, access tokens expire after 1 hour afaik. If we find the endpoint, we will update it asap!
