### ISSUE TITLE
"X-Riot-ClientVersion" header changes every update.

### ISSUE THREAD

**Issue by BobbyESP** [Sprayxe/valorant.js#8]
That header changes every update and it is needed to get all the items (cause the versions includes new items kek). So, Officer has a Valorant API that gives u the version; maybe its a good option to put it instead of updating the library every time that a update gets launched.

This is the url: https://dash.valorant-api.com

And this is the request (GET, of course): https://valorant-api.com/v1/version

The problem, it needs to be formatted like i have in the line 454 of the file src/main/valorant/index.js

**Comment by FPilica** [comment]
I will implement this in ~a week after I am done with my exams

**Comment by BobbyESP** [comment]
okk

**Comment by BobbyESP** [comment]
btw, if i can try to implemt it by myself, i will made a pull request. later i'll.
