### ISSUE TITLE
Content-Service URL Change

### ISSUE THREAD

**Issue by LastPlayerTR** [Sprayxe/valorant.js#9]
Error: { data: {"message":"Failed to get all items from the game","type":"INFO_GETITEMS_FAIL","code":70002}, error: Error: Request failed with status code 404 }

**Comment by BobbyESP** [comment]
lemme check this

**Comment by BobbyESP** [comment]
Ok, i think it's fixed, Now i need to wait for Sprayxe's approve.

**Comment by marcel-wrld** [comment]
Sorry, I didn‘t read my emails. I‘m gonna update the library on npm tomorrow

**Comment by marcel-wrld** [comment]
Updated npm, update your npm package and see if it works. (npm i valorant.js)

**Comment by BobbyESP** [comment]
Spray, i think it won't work because the client version is outdated and i made a pull request another time updating it. Im doing too the auto upadter of the client version that gets the ClientVersion from Valornat-API.com API.

**Comment by marcel-wrld** [comment]
I will update the lib today so it gets the client version by itself

**Comment by marcel-wrld** [comment]
I‘m gonna be rewriting this library in typescript to fix all issues. So I am closing this for now
